platform :ios, '11.0'
use_frameworks!

target 'AMPTracker_Example' do
  pod 'AMPTracker/Amplitude', :path => '../'

  target 'AMPTracker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'Amplitude'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
